name: ShellCheck
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck-alpine:stable
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: ./shellcheck.sh
